apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-e7cu
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-e7cu@sha256:60fbe633ea650385214446ad7e1151f0249dc285eff666512a9b1b3ddc21307a
        name: my-nodejs
        resources: {}
status: {}
